# permissions for end users to view replicatedresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicatedresource-viewer-role
rules:
- apiGroups:
  - utils.simopolis.xyz
  resources:
  - replicatedresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - utils.simopolis.xyz
  resources:
  - replicatedresources/status
  verbs:
  - get
