
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - utils.simopolis.xyz
  resources:
  - replicatedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - utils.simopolis.xyz
  resources:
  - replicatedresources/finalizers
  verbs:
  - update
- apiGroups:
  - utils.simopolis.xyz
  resources:
  - replicatedresources/status
  verbs:
  - get
  - patch
  - update
